skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_factory = "9VptbChe2mPw3fkmcnKxCShNmagw4F8YvNX3BzSrPKQF"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
