[package]
name = "init_oracle"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anchor-lang = "1.1.2"
anyhow = "1"
solana-client = "3"
solana-commitment-config = "3.1.1"
solana-keypair = "3"
solana-sdk = "3"
solana-signer = "3"
solana-transaction = { version = "3", features = ["bincode"] }
token_factory = { path = "../../programs/token_factory", default-features = false, features = ["cpi"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
