import { AnchorProvider, BN, Program } from '@coral-xyz/anchor'
import type { Wallet } from '@coral-xyz/anchor'
import { Connection, Keypair, PublicKey, Transaction } from '@solana/web3.js'

// Anchor build artifacts (regenerated by `anchor build`).
import idl from '../../../target/idl/token_factory.json'
import type { TokenFactory } from '../../../target/types/token_factory'

import { RPC_URL } from './constants'

export interface CreateTokenWithFeeParams {
  payer: PublicKey
  decimals: number
  initialSupply: bigint
  feeUsd: bigint
}

export interface CreateTokenWithFeeResult {
  transaction: Transaction
  mint: Keypair
}

/** Only builds instructions/transactions — never asked to sign, so it doesn't need a real wallet. */
function unsignedWallet(publicKey: PublicKey): Wallet {
  const fail = () => {
    throw new Error('this provider is instruction-building only; sign via the connected wallet instead')
  }
  return { publicKey, signTransaction: fail, signAllTransactions: fail } as unknown as Wallet
}

function getProgram(payer: PublicKey): Program<TokenFactory> {
  const connection = new Connection(RPC_URL, 'confirmed')
  const provider = new AnchorProvider(connection, unsignedWallet(payer), { commitment: 'confirmed' })
  return new Program(idl as TokenFactory, provider)
}

/** Mirrors CreateTokenWithFee in programs/token_factory/src/instructions/create_token.rs */
export async function buildCreateTokenWithFeeTx({
  payer,
  decimals,
  initialSupply,
  feeUsd,
}: CreateTokenWithFeeParams): Promise<CreateTokenWithFeeResult> {
  const program = getProgram(payer)
  const mint = Keypair.generate()

  const instruction = await program.methods
    .createTokenWithFee(decimals, new BN(initialSupply.toString()), new BN(feeUsd.toString()))
    .accounts({ mint: mint.publicKey, payer })
    .instruction()

  const { blockhash, lastValidBlockHeight } = await program.provider.connection.getLatestBlockhash()
  const transaction = new Transaction({ feePayer: payer, blockhash, lastValidBlockHeight }).add(instruction)
  transaction.partialSign(mint)

  return { transaction, mint }
}
